# action.yml
name: 'CentOS8 with Java 17'
description: 'Docker container for building on CentOS with Java 17'

inputs:
  command:
    description: 'Command to run'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}